rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
  - gemfiles/Gemfile-activemodel-3.0.x
  - gemfiles/Gemfile-activemodel-3.1.x
  - gemfiles/Gemfile-activemodel-3.2.x
  - gemfiles/Gemfile-activemodel-4.0.x
  - gemfiles/Gemfile-activemodel-4.1.x
