name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0' ]
        rails: [ '4.2', '5.0', '5.1', '5.2', '6.0', '6.1' ]
        exclude:
          - ruby: '2.6'
            rails: '4.0'
          - ruby: '2.6'
            rails: '4.1'
          - ruby: '2.7'
            rails: '4.0'
          - ruby: '2.7'
            rails: '4.1'
          - ruby: '2.7'
            rails: '4.2'
          - ruby: '3.0'
            rails: '4.0'
          - ruby: '3.0'
            rails: '4.1'
          - ruby: '3.0'
            rails: '4.2'
          - ruby: '3.0'
            rails: '5.0'
          - ruby: '3.0'
            rails: '5.1'
          - ruby: '3.0'
            rails: '5.2'

    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile-activemodel-${{ matrix.rails }}.x
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache gems

    - name: RSpec
      run: bundle exec rake
